#include <stdio.h>
typedef struct primary_s primary_t;
typedef struct primary_globals_s primary_globals_t;
typedef struct secondary_s secondary_t;
int primary_func(primary_t *self, secondary_t b);
void *primary_bunc(primary_t *self);
int secondary_func(primary_t *self, secondary_t b);
primary_globals_t primary_globals;
int C = 20;

// TODO @(dleiferives,5e7b1b5c-f78d-4ff0-811d-680bb0ef544b): add support for
// nested structs / namespaces :dcc: ~#

struct primary_s {
     secondary_t *a;
     primary_t *b;
};

struct secondary_s {
     secondary_t *a;
     secondary_t *b;
};

int primary_func(primary_t *self, secondary_t b) {
    return 10;
}



void *primary_bunc(primary_t *self) {
    return (void*)0;
}



struct primary_globals_s {
     secondary_t c;
     primary_t d;
};


int secondary_func(primary_t *self, secondary_t b) {
    return 10;
}

int main(){
    printf("%d\n",C);
    return 0;
}



///////////////////////////////////////
// test_predeclaration.c autogenerated from test_predeclaration.d: 
// 
// 
// 
// // TODO @(dleiferives,5e7b1b5c-f78d-4ff0-811d-680bb0ef544b): add support for
// // nested structs / namespaces :dcc: ~#
// 
// struct primary{
//     secondary a;
//     primary *b;
//     secondary @c;
//     primary @d;
// 
//     int @func(primary *self, secondary b){
//         return 10;
//     };
// 
//     void *@bunc(primary *self){
//         return;
//     };
// 
// };
// 
// struct secondary{
//     primary a;
//     secondary *b;
// 
//     int @func(primary *self, secondary b){
//         return 10;
//     };
// };
