
int Goomba_member() {
    return 10;
}



int main(){
    void * a = &(Goomba_member);
}

///////////////////////////////////////
// test_member_function_pointer.c autogenerated from test_member_function_pointer.d: 
// struct Goomba{
//     int @member(){
//         return 10;
//     };
// };
// 
// 
// int main(){
//     void * a = &Goomba@member;
// }
